name: "Copy Matching Files"
description: "Copy files from a source directory to a destination if they match given filenames"
author: a3.services
inputs:
  source:
    description: "Source directory containing files"
    required: true
  dest:
    description: "Destination directory to copy matching files into"
    required: true
  match:
    description: "Array of filenames to match exactly"
    required: true
    type: array
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p "${{ inputs.dest }}"

        for file in "${{ inputs.source }}"/*; do
          fname=$(basename "$file")

          for pat in "${{ inputs.match[@] }}"; do
            if [[ "$fname" == $pat ]]; then
              cp "$file" "${{ inputs.dest }}/"
              echo "Copied: $fname → ${{ inputs.dest }}"
              break
            fi
          done
        done
