name: "Copy Matching Files"
description: "Copy files from a source directory to a destination if they match given filenames"
author: a3.services
inputs:
  source:
    description: "Source directory containing files"
    required: true
  dest:
    description: "Destination directory to copy matching files into"
    required: true
  match:
    description: "Array of filenames to match exactly"
    required: true
    type: array
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p "${{ inputs.dest }}"

        readarray -t MATCHES <<< "${{ inputs.match }}"

        for FILE in "${{ inputs.source }}"/*; do
          FILE_NAME=$(basename "${FILE}")
          echo "....."
          echo ${FILE_NAME}
          echo 

          for MATCH in "${MATCHES[@]}"; do
            if [[ "${FILE_NAME}" == ${MATCH} ]]; then
              cp "${FILE}" "${{ inputs.dest }}/"
              echo "Copied: ${FILE_NAME} → ${{ inputs.dest }}"
              break
            fi
          done
        done
